config/routes.rb
Rails.application.routes.draw do
  get 'stats', to: 'stats#index'
  get 'versions', to: 'versions#index'

  resources :events do
    get :cancel, on: :member
    post :preview, on: :collection, to: 'events#preview_create'
    patch :preview, on: :member
  end
  resources :moderations do
    resources :notes, only: %i[new create]
    patch :preview, on: :member
    get :validate, :refuse, on: :member
    put :accept, on: :member
  end
  resources :digests, only: %i[index show]
  resources :regions, only: %i[index]
  get 'tags/orgas', to: 'tags#orgas'
  resources :tags, only: %i[index show]
  resources :maps, only: %i[index show]
  resources :orgas do
    get :cancel, :validate, :refuse, on: :member
    put :accept, on: :member
  end

  get 'showevent.php', to: redirect { |_, req| "events/#{req.params[:id]}" }
  get 'listevents.php', to: redirect { |_, req| "events?#{req.query_string}" }
  get 'editevent.php', to: redirect(lambda do |_, req|
    "events/#{req.params[:id]}/edit?secret=#{req.params[:secret]}"
  end)
  get '(:format)listevents.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get 'event.php',
      to: redirect { |_, r| "events?#{r.query_string}" }
  get '(:format)event.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get '(:format).php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit',
        as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'events#index'

end

app/views/layouts/_flash.html.haml
#flash-messages
  - flash.each do |key, value|
    .flash(class="#{key}")= raw value

app/views/layouts/application.html.haml
!!! 5
/[if IE]
%html.no-js{ lang: I18n.locale, class: params[:iframe] ? 'iframe' : '' }
  %head
    %meta(charset='utf-8')
    %meta(name='viewport' content='width=device-width, initial-scale=1.0')
    %meta(name='robots' content='index, follow')

    = display_meta_tags site: t('.title')

    = favicon_link_tag '/favicon.ico'
    = auto_discovery_link_tag :rss, controller: '/events', format: :rss

    = stylesheet_link_tag 'application', media: 'all',
      'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  - sub = request.domain ? request.domain.split('.')[0] : ''
  %body{ class: [sub, controller_name, action_name, params[:tag]] }
    %header.top
      %nav
        = render '/regions/filter'
        = render '/pages/search'

      = link_to root_path do
        = image_tag 'baby_gnu_adl.png', alt: '', class: :logo
      %h1= link_to t('.title'), root_path
      %h2= t '.subtitle'

    = render 'layouts/flash', flash: flash if flash.present?

    %main= yield

    %footer.bottom
      %nav
        = link_to new_event_path do
          %em.fa.fa-pencil-alt
          = t '.propose'
        = link_to new_orga_path do
          %em.fa.fa-users
          = t '.propose_orga'
        %br/
        = link_to maps_path do
          %em.fa.fa-map
          = t '.map'
        = link_to tags_path do
          %em.fa.fa-tags
          = t '.tags'
        = link_to orgas_path do
          %em.fa.fa-users
          = Orga.model_name.human.pluralize
        = link_to versions_path do
          %em.fa.fa-history
          = t 'versions.index.title'
        = link_to page_path('infos') do
          %em.fa.fa-info
          = t '.infos'
        = link_to stats_path do
          %em.fa.fa-signal
          = t '.stats'
        = link_to page_path('contact') do
          %em.fa.fa-envelope
          = t '.contact'
        = link_to moderations_path do
          %em.fa.fa-gavel
          = t '.moderation'

    =  piwik_tracking_tag